name: React CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run ESLint Security Check
      run: npx eslint .

    - name: Build React Application
      run: npm run build
      
    - name: Build Docker image
      run: docker build -t xandao6/puc-web .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push xandao6/puc-web

    - name: Notify Discord on Deployment
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        message: 'Deployment successful: ${{ github.event.head_commit.message }}'

