name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run a one-line script
      run: echo "Hello, world!"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        echo "Running tests"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Fake Deploy
      run: |
        echo "Deploying application"
